server:
  port: 8761
eureka:
  client:
    register-with-eureka: false  # 不注册到eureke 这是服务端
    fetch-registry: true  # eureka集群同步，默认true
    service-url:
      defaultZone: http://47.112.124.205:${server.port}/eureka/,http://120.79.74.127:${server.port}/eureka/,http://118.24.229.84:${server.port}/eureka/

#日志配置
logging:
  config: classpath:springConfig/logback.xml

#用户认证
